---
- hosts: centos01
  become: true
  gather_facts: false
  vars:
    dict:
      dict_key01: value01
  tasks:
    - name: create file
      copy:
        src: test.txt
        dest: /tmp/test.txt
        state: file
      register: sdfile
    - name: debugging
      debug: 
        msg: "{{ sdfile }}"
    - name: named dict
      debug:
        msg: "{{ dict }}"
    - name: named dict with key value . notation
      debug:
        msg: "{{ dict.dict_key01 }}"
    - name: named dict with brackets notation
      debug:
        msg: "{{ dict['dict_key01'] }}"
...