---
- hosts: centos01
  become: true
  tasks:
    - name: motd
      copy:
        src: centos_motd
        dest: /etc/motd

    - name: copy to diff location
      copy:
        src: centos_motd
        dest: /tmp/testnew.txt

    - name: Remove file
      file:
        path: /tmp/test.txt
        state: absent
...