---
- hosts: centos01
  become: true
  gather_facts: false
  vars:
    motd_var: MOTD playbook Stuff
  tasks:
    - name: motd
      copy:
        content: "{{ motd_var }}"
        dest: /etc/motd
      notify: MOTD Notification
  handlers:
    - name: MOTD Notification
      debug:
        msg: MSG received
    - name: SKYDEVOPS
      debug:
        msg: skydevops
...