---
- hosts: centos01
  become: true
  tasks:
    - name: motd
      copy:
        src: centos_motd
        dest: /etc/motd
        
    - name: copy to diff location
      copy:
        src: centos_motd
        dest: /tmp/test.txt
...