---
- hosts: centos01
  become: true
  gather_facts: false
  vars:
    dict:
      dict_key01: value01
  tasks:
    - name: create file
      copy:
        src: test.txt
        dest: /tmp/test.txt
      register: sdfile
    - name: debugging
      debug: 
        msg: "{{ sdfile }}"
    - name: named dict with key value . notation
      debug:
        msg: "{{ sdfile.diff.after.path }}"
    - name: named dict with brackets notation
      debug:
        msg: '{{ sdfile[diff]["after"][path] }}'
...