---
- hosts: linux
  gather_facts: true

  tasks:
  - name: Testing HostVars
    debug:
      msg: "{{ hostvars[ansible_hostname].shashi | default('22')}}"
  - name: Testing Group vars
    debug:
      msg: "{{ ansible_user | default('shashi') }}"
...