---
- hosts: centos01
  become: true
  gather_facts: false
  vars:
    sdlist:
      - item01
      - item02

  tasks:
    - name: Inline dict
      debug:
        msg: "{{ sdlist }}"
    - name: named dict with key value . notation
      debug:
        msg: "{{ sdlist.0 }}"
    - name: named dict with brackets notation
      debug:
        msg: "{{ sdlist[0] }}"
...