---
- hosts: linux
  tasks:
  - name: Register OUTPUT
    command: hostname -s
    when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7') or (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '16')
...
    