---
- hosts: all
  tasks:
    - name: Jinja2 Syntactical Excercises - IF Statement
      debug:
        msg: >
            --== IF statement with elif ==--
            {# --== Jinja2 IF statement ==-- #}
            {# IF the HOSTNAME is control, include a message -#}
            {% if ansible_hostname == "controlhost" -%}
                This is the controlhost
            {% elif ansible_hostname == "centos01" -%}
                This belongs to RedHat Family
            {%elif ansible_hostname == "ubuntu01" -%}
                This belongs to Debian Family
            {% endif %}
